### ISSUE TITLE
Localize ICS Files

### ISSUE THREAD

**Issue by ay8s** [sportstimes/f1#109]
Using the locale files we can now generate localized ics files and generate each file at build time.

**Comment by HarDX** [comment]
one question: about generate,
for example
SUMMARY:(TBC) First Practice Session (Austrian Grand Prix Grand Prix)

maybe not need ...  Grand Prix and Grand Prix? only Austrian Grand Prix

**Comment by ay8s** [comment]
👍  I spotted that yesterday, I think it is resolved in https://github.com/sportstimes/f1/pull/112
