### ISSUE TITLE
Font for Footer Support - LeagueSpartan has no cyrillic symbols

### ISSUE THREAD

**Issue by HarDX** [sportstimes/f1#114]
Font for Footer Support - LeagueSpartan has no cyrillic symbols, and ugly... on Russian (

**Comment by ay8s** [comment]
Does this effect the header also? We can look at a fallback when using Russian.

**Comment by HarDX** [comment]
> Does this effect the header also

yes
![image](https://user-images.githubusercontent.com/5231223/85064736-6dfa1100-b1c5-11ea-83f0-4085af51ec3f.png)

![image](https://user-images.githubusercontent.com/5231223/85064746-75b9b580-b1c5-11ea-9c38-150fc7c29829.png)

**Comment by ay8s** [comment]
@HarDX Does this look better? https://share.buffer.com/xQuDAQ5B :)

**Comment by HarDX** [comment]
Yes

**Comment by HarDX** [comment]
Same problem exist again.
