### ISSUE TITLE
Link to localized ICS files within Generate

### ISSUE THREAD

**Issue by ay8s** [sportstimes/f1#117]

**Comment by HarDX** [comment]
Do you have any news?

**Comment by sigito** [comment]
Could you share details? Is it that the event names in the calendar are localized as well?

**Comment by ay8s** [comment]
@sigito It is yup. We have this completed but I'm just digging into whether its going to be sustainable for us to do this with all of the variations of calendar files which need to be generated. 

I may look into reducing the number of time options available which will reduce the number of variations considerably and improve generation and deployment times as we continue to add languages.

**Comment by ay8s** [comment]
Will go live in #248

**Comment by ay8s** [comment]
Merged into #248 for 2021 👍
