### ISSUE TITLE
Missing F1 pre-season testing

### ISSUE THREAD

**Issue by Pau-Marin** [sportstimes/f1#1225]
Hello!

I've noticed that the 3 pre-season testing sessions (https://www.formula1.com/en/racing/2023/Pre-Season-Test.html) don't seem to appear on the calendar (at least not in spanish).

**Comment by ay8s** [comment]
Thanks @Pau-Marin. We've played around with showing these in the past but decided to leave them off. 

We may explore adding tests in the future if we see more demand for it.
