### ISSUE TITLE
Czech Subscribe.json translations

### ISSUE THREAD

**Issue by ay8s** [sportstimes/f1#133]
We added a new page which enables users to subscribe for email reminders.

https://github.com/sportstimes/f1/blob/master/locales/en/subscribe.json

There is also a new string under common.json for options.email. https://github.com/sportstimes/f1/blob/master/locales/en/common.json#L10

**Comment by ay8s** [comment]
Hey @adamhoustava. Thanks for your help before! Would you be able to help us with a few new strings?

**Comment by adamhoustava** [comment]
@ay8s yeah, I can do it.

**Comment by ay8s** [comment]
Closing this one for now, will need to add an issue for each language for 2021 with the upcoming site changes. 👍  Feel free to still tackle if you want before then.
