### ISSUE TITLE
Dutch Subscribe.json translations

### ISSUE THREAD

**Issue by ay8s** [sportstimes/f1#134]
We added a new page which enables users to subscribe for email reminders.

https://github.com/sportstimes/f1/blob/master/locales/en/subscribe.json

There is also a new string under common.json for options.email. https://github.com/sportstimes/f1/blob/master/locales/en/common.json#L10

**Comment by ay8s** [comment]
@stijndp Curious if you'd be able to help with these at all? :)

**Comment by stijndp** [comment]
I'm an old fart SVN guy but I think I should have done it correctly so that the 2 new strings in calender.json and common.json and also the new subscribe.json can be pulled into the main.

**Comment by ay8s** [comment]
Thanks @stijndp, good old subversion 👍  

Merged and deploying those now. 👏
