### ISSUE TITLE
Spanish Subscribe.json translations

### ISSUE THREAD

**Issue by ay8s** [sportstimes/f1#135]
We added a new page which enables users to subscribe for email reminders.

https://github.com/sportstimes/f1/blob/master/locales/en/subscribe.json

There is also a new string under common.json for options.email. https://github.com/sportstimes/f1/blob/master/locales/en/common.json#L10

**Comment by ay8s** [comment]
Hey @slopezm. Thanks for your help with the Spanish translations before, we've added a few new strings and I wondered if you could help out again? 👍

**Comment by slopezm** [comment]
Glad to. Can you assign the task to me? I'll work on it tomorrow

**Comment by ay8s** [comment]
Thanks @slopezm 👏
