### ISSUE TITLE
French Subscribe.json translations

### ISSUE THREAD

**Issue by ay8s** [sportstimes/f1#136]
We added a new page which enables users to subscribe for email reminders.

https://github.com/sportstimes/f1/blob/master/locales/en/subscribe.json

There is also a new string under common.json for options.email. https://github.com/sportstimes/f1/blob/master/locales/en/common.json#L10

**Comment by ay8s** [comment]
Hey @DeadEye0112, we've added a couple new strings to the site. Would you be able to help us again? 🙌

**Comment by DeadEye0112** [comment]
Sure, I'm on it!
