### ISSUE TITLE
Croatian Subscribe.json translations

### ISSUE THREAD

**Issue by ay8s** [sportstimes/f1#137]
We added a new page which enables users to subscribe for email reminders.

https://github.com/sportstimes/f1/blob/master/locales/en/subscribe.json

There is also a new string under common.json for options.email. https://github.com/sportstimes/f1/blob/master/locales/en/common.json#L10

**Comment by Marko-HR** [comment]
Translated. 

You should change "hrvatski jezik" to "Hrvatski" in language drop down menu.

**Comment by ay8s** [comment]
> You should change "hrvatski jezik" to "Hrvatski" in language drop down menu.

Will look into this, right now it's dynamic.
