### ISSUE TITLE
Italian Subscribe.json translations

### ISSUE THREAD

**Issue by ay8s** [sportstimes/f1#138]
We added a new page which enables users to subscribe for email reminders.

https://github.com/sportstimes/f1/blob/master/locales/en/subscribe.json

There is also a new string under common.json for options.email. https://github.com/sportstimes/f1/blob/master/locales/en/common.json#L10

**Comment by ay8s** [comment]
Hey @ffaamm, curious if you may be able to help us with these new strings? 👍

**Comment by ffaamm** [comment]
Yes, I’ll look at them soon.

**Comment by ffaamm** [comment]
Pull request sent, enjoy!

**Comment by ay8s** [comment]
Thanks @ffaamm 👏
