### ISSUE TITLE
German Subscribe.json translations

### ISSUE THREAD

**Issue by ay8s** [sportstimes/f1#139]
We added a new page which enables users to subscribe for email reminders.

https://github.com/sportstimes/f1/blob/master/locales/en/subscribe.json

There is also a new string under common.json for options.email. https://github.com/sportstimes/f1/blob/master/locales/en/common.json#L10

**Comment by ay8s** [comment]
@LsHallo @schoenpat Thanks for your help on our German strings, we've added a few new strings for our email reminders. Would you be able to help us fill in the gaps? 👍

**Comment by schoenpat** [comment]
Yes, no problem. I will create a PR.
