### ISSUE TITLE
Russian Subscribe.json translations

### ISSUE THREAD

**Issue by ay8s** [sportstimes/f1#140]
We added a new page which enables users to subscribe for email reminders.

https://github.com/sportstimes/f1/blob/master/locales/en/subscribe.json

There is also a new string under common.json for options.email. https://github.com/sportstimes/f1/blob/master/locales/en/common.json#L10

**Comment by ay8s** [comment]
Hey @HarDX. I've just merged in our new email reminder subscription form. I wondered if you'd be able to help us with a couple new strings? Thanks 👍

**Comment by HarDX** [comment]
https://github.com/sportstimes/f1/pull/145#issue-440902650
