### ISSUE TITLE
F1 is missing round 4

### ISSUE THREAD

**Issue by witnessmenow** [sportstimes/f1#1419]
Hello

Just a heads up that the rounds in the F1 json file is missing round 4

```
      "name": "Australian",
      "location": "Melbourne",
      "latitude": -37.8373,
      "longitude": 144.9666,
      "round": 3,
      "slug": "australian-grand-prix",
      "localeKey": "australian-grand-prix",
      "sessions": {
        "fp1": "2023-03-31T01:30:00Z",
        "fp2": "2023-03-31T05:00:00Z",
        "fp3": "2023-04-01T01:30:00Z",
        "qualifying": "2023-04-01T05:00:00Z",
        "gp": "2023-04-02T05:00:00Z"
      }
    },
    {
      "name": "Azerbaijan",
      "location": "Baku",
      "latitude": 40.3699,
      "longitude": 49.8433,
      "round": 5,
      "slug": "azerbaijan-grand-prix",
      "localeKey": "azerbaijan-grand-prix",
      "sessions": {
        "fp1": "2023-04-28T09:30:00Z",
        "qualifying": "2023-04-28T13:00:00Z",
        "sprintQualifying": "2023-04-29T08:30:00Z",
        "sprint": "2023-04-29T13:30:00Z",
        "gp": "2023-04-30T11:00:00Z"
      }
```
And continues from here for the rest of the calendar

Not sure it's worth doing anything about it, not sure if the round are surfaced anywhere

Not a bug, but thought it was unusual to remove Imola rather than keeping it with the cancelled flag. This also leaves a gap in the rounds without any context to why (unless you just know Imola was cancelled). Displaying Imola or not seemed to me more like an UI decision 

Thank you for all the work on this! I'm using the data to create a display with all the session times with an Arudino (ESP32)

![image](https://github.com/sportstimes/f1/assets/1562562/94422966-b2ab-4a8d-8cbc-0188a26738f8)

**Comment by ay8s** [comment]
We don't really use the rounds on our side. We tend to mark them as cancelled for a week or two and then remove them just to clean things up within the UI. The canceled flag doesn't behave super well within the layout on mobile devices so it was quicker to remove and revisit fixing that later.

We'll look at updating the round numbers next time we come to update the json. 

Neat project! Do you access that json directly via GitHub or did you discover the https://f1calendar.com/api/year/2023 url.

**Comment by witnessmenow** [comment]
Cool, yeah no worries, I wasn't sure it was being used anywhere, just thought I'd raise it when I saw it.

No problem about Imola situation either, it also doesn't impact my use case as I just show the next race.

Cheers! I fetch the json file from GitHub. I didn't want to assume it was ok to add additional load to your server so I didn't even look into the underlying apis etc. 

There is also a chance that additional people will make the project too, so while it might be ok for one Arduino to be hitting the server, if there is a bunch it might add too much.

The code for it is here if your interested: https://github.com/witnessmenow/F1-Arduino-Notifications

**Comment by ay8s** [comment]
Honestly it should be fine @witnessmenow. We're well within our limits and are fortunate to be sponsored by Vercel. We heavily cache the API routes so it's effectively pulling down a static file as long as it's only refreshing periodically with a sensible time between unlike Google Calendar who seem to refresh way too often. 😆
