### ISSUE TITLE
Formula 2 & 3

### ISSUE THREAD

**Issue by scottrobertson** [sportstimes/f1#181]
It would be awesome to have this for Formula 2 and 3 too.

**Comment by ay8s** [comment]
Thanks for the validation @scottrobertson 👍  

I'm actually working on this quite a bit, making the actual race listings a little more dynamic based on environment variables. https://github.com/sportstimes/f1/tree/feature/multiple-sites

We've got a bunch of domain names, unfortunately we didn't manage to grab f2calendar.com and were outbid last minute with the seller now asking for $3k 😞.

I'm also waiting on a new beta feature from Vercel our hosting company which will allow us to deploy this repository to multiple projects. So this single repository can power each of the sites.

**Comment by scottrobertson** [comment]
Glad to hear it :)

Could you maybe get a generic domain instead with different sections? Would simplify things a huge amount for you in terms of deployments.

**Comment by ay8s** [comment]
Once configured it should be pretty straight forward with a merge to master deploying to each domain automatically. But we're on the look out for some more decent domains. 👍 

I'd also love to get Formula E and W Series on the list also. If you have any domain suggestions please drop them over. :D

**Comment by JefersonMolinari** [comment]
Not sure if this fits what you looking for, but _calendarf2.com_ is available, also available:

- calendarf1.com
- calendarf2.com
- calendarf3.com
- calendarfe.com
- calendarfw.com

**Comment by ay8s** [comment]
Thanks @JefersonMolinari. I have a couple of domains registered which I think will work and keep them in the similar format. Just waiting on a new feature from our hosting company before rolling one or two of them out.

**Comment by ay8s** [comment]
Coming as part of #248

**Comment by mzso** [comment]
[**@scottrobertson**](https://github.com/scottrobertson) commented on [2020. júl. 6. 20:06 CEST](https://github.com/sportstimes/f1/issues/181#issuecomment-654386131 "2020-07-06T18:06:05Z - Replied by Github Reply Comments"):
> Glad to hear it :)
> 
> Could you maybe get a generic domain instead with different sections? Would simplify things a huge amount for you in terms of deployments.

I see no issue with f1calendar.com/FE or such. Probably most people will continue to search for F1 first anyway.

**Comment by scottrobertson** [comment]
Any news on when this will be available?

**Comment by ay8s** [comment]
@scottrobertson Quietly we have the sites up already but we're waiting on confirmation of a few more times. Seems getting official session times is a little trickier for F2 and F3. 

https://f2cal.com
https://f3calendar.com

**Comment by mzso** [comment]
[**@ay8s**](https://github.com/ay8s) commented on [2021. márc. 11. 19:18 CET](https://github.com/sportstimes/f1/issues/181#issuecomment-796942500 "2021-03-11T18:18:20Z - Replied by Github Reply Comments"):
> [@scottrobertson](https://github.com/scottrobertson) Quietly we have the sites up already but we're waiting on confirmation of a few more times. Seems getting official session times is a little trickier for F2 and F3.
> 
> [https://f2cal.com](https://f2cal.com)  
> [https://f3calendar.com](https://f3calendar.com)
> 
> Once we have some stuff confirmed I'll be adding a quick way to navigate between the sites.

No FE yet? I guess the [preview URL](https://formulae-git-task-formula-e-sportstimes.vercel.app/) is not updated with new data.

**Comment by ay8s** [comment]
@mzso Similar issue to the other race series. Just finding a lack of actual times. In the next couple of weeks I'll be slotting in a component to navigate between the sites and will hopefully have more confirmed times available. https://formulaecal.com
