### ISSUE TITLE
Domain-agnostic calendar links

### ISSUE THREAD

**Issue by si** [sportstimes/f1#2]
When testing on the dev.f1calendar.com sub-domain, it's referencing the production domain which makes it trickier to test calendar subscriptions and downloads (webcal, Google and download)

e.g. https://github.com/sportstimes/f1/blob/d71ff1d62bce18dce1ea0218aab92c1a39d90ed8/pages/generate.js#L31

Can we replace this with the environment sub-domain or even just make URLs relative?

**Comment by ay8s** [comment]
https://github.com/sportstimes/f1/commit/80f39a4968a97c08e6bdc21b1c1c7569230546bf
