### ISSUE TITLE
Long donation text wrap issue on mobile for Donation button

### ISSUE THREAD

**Issue by lumbytyci** [sportstimes/f1#231]
As you can see from the image, there is a small graphical issue with text wrapping for the donation button when text is long for mobile devices.
![problem_text_wrap](https://user-images.githubusercontent.com/17204788/89760278-5451b780-daec-11ea-9c4e-bf64fa8f222b.png)

**Comment by lumbytyci** [comment]
Potential fix by simply changing anchor into inline-block in `Footer.module.scss`. I can make a PR if you wish.

![potential_fix](https://user-images.githubusercontent.com/17204788/89796018-67cf4380-db29-11ea-9ea7-1663312c2620.png)

**Comment by ay8s** [comment]
Thanks @lumbytyci. Will have this fixed up in a bunch of updates for 2021 as part of #248 . 👍

**Comment by lumbytyci** [comment]
> 
> 
> Thanks @lumbytyci. Will have this fixed up in a bunch of updates for 2021 as part of #248 . 👍

Great, it's best if I don't touch any front-end stuff :)
