### ISSUE TITLE
"Select language" text

### ISSUE THREAD

**Issue by petosorus** [sportstimes/f1#254]
Hello!

First, thanks for the website and the huge service.

Second, I'm noticing in four languages, the "Select language" text is kept as "Select language" in english. I have no problem with this, but the others languages translate it.

Is there a prefered behavior?

Cheers

**Comment by ay8s** [comment]
@petosorus It'd be great to have it translated in all languages. I'll check if there's anything stopping people from doing that.

**Comment by petosorus** [comment]
Hey! Sorry for the late answer.

That's cool. I'll do the French one,  but is it okay if I wait for october to open the PR? Hacktoberfest is nice, but finding 4 PRs is hard sometimes ^^

**Comment by ay8s** [comment]
Sure @petosorus 👍

**Comment by ay8s** [comment]
Closing this one for now, we'll likely need a task for each language for 2021 as we'll be adding support for a bunch of other race series.
