### ISSUE TITLE
How data is updated?

### ISSUE THREAD

**Issue by CyrilNb** [sportstimes/f1#286]
Hello, 

first, good job for the website and public repo. 
Just have a quick question, how is the data updated? I see commits where you manually corrected some dates, but at first did you all put this manually?

Would it be painful to add winner of each race?
A automatic way would be awesome (pull data from official website maybe..?)

**Comment by ay8s** [comment]
@CyrilNb Data is pulled in manually. Especially this year it would've been tricky to automate this.

As for winners, it is something I've thought about but in the interest of keeping it simple I've left it out for now. Potentially could see us linking to race reports elsewhere if there was interest in it.
