### ISSUE TITLE
Incorrect calendar times in local timezones

### ISSUE THREAD

**Issue by si** [sportstimes/f1#3]
Right, finally found time to test the timezones and calendar times on my Mac using https://dev.f1calendar.com/.

Here are my results:

- **China** - 2 hours too early (9am in cal, 11am on corp) on all but race
- **Canada** - third practice, qualifier & race time 1hr late (12pm, 3pm & 3:10pm in cal, 11am, 2pm & 2:10pm on corp)
- **Austria** - 1st is 2am in cal, 11am on corp
- **Great Britain** - 1st, 2nd, 3rd and qual all 1hr early
- **Mexico** - 1st & 2nd 1hr early (10am & 2pm in cal, 11am & 3pm on corp)
- **Brazil** - race 1hr late (3:10pm in cal, 2:10pm on corp)

**Comment by ay8s** [comment]
Fixed! 👍
