### ISSUE TITLE
Redirect www to non-www domain

### ISSUE THREAD

**Issue by si** [sportstimes/f1#36]
At the moment, both domains are live:

- https://f1calendar.com/
- https://www.f1calendar.com/

We should 301 redirect https://www.f1calendar.com/ to https://f1calendar.com/ for SEO reasons (Google already list non-www)

**Comment by ay8s** [comment]
Added a redirect in the Zeit dashboard. :)

**Comment by si** [comment]
Nice one. Can you provide me access as well?
