### ISSUE TITLE
Webcal does not work in Outlook.com

### ISSUE THREAD

**Issue by Haribo112** [sportstimes/f1#449]
Outlook.com allows one to add a calendar in webcal://xxxx.ics form, so I copied the [webcal link](webcal://f1calendar.com/download/f1-calendar_p1_p2_p3_q_gp.ics) from f1calendar.com and imported it as a new calendar called 'F1 2021'. However, this calendar is now empty.

My endgoal would be to have the F1 events in a separate calendar that I can view on both my PC (Outlook / Office 365) and my phone (Outlook app). What would be the best way to do so?

**Comment by ay8s** [comment]
@Haribo112 Thanks for reporting. Curious if you picked a particular language or if you were just trying to import the default English Calendar?

With these settings I was able to successfully import the calendar into a Outlook.com calendar and see this weekend's upcoming sessions.
![Screen Shot 2021-03-23 at 9 24 40 PM](https://user-images.githubusercontent.com/1058408/112254789-65d07580-8c1e-11eb-94ab-7bad1d485a2a.png)

**Comment by Haribo112** [comment]
I see, you use the http:// link instead of the webcal:// link. Maybe that's the trick. Outlook does say I should use the webcal:// link, but I will try with the http:// one.

**Comment by Haribo112** [comment]
Can confirm that your method works great. Thanks for the help!

**Comment by ay8s** [comment]
Great to hear @Haribo112. I'll dig in and see why webcal:// doesn't work to hopefully avoid this in the future.
