### ISSUE TITLE
Practice sessions are included in a generated iCal for F2, even when only race sessions are selected

### ISSUE THREAD

**Issue by jmcgreevy42** [sportstimes/f1#515]
The iCal linked below includes F2 practice sessions in addition to the sprint and feature races, even though the practice sessions are not selected when generating the calendar.

https://f2cal.com/download/f2-calendar_sprint1_sprint2_feature.ics

Steps to reproduce: 

1. Go to https://f2cal.com/generate
2. Deselect "Practice" and "Qualifying"
3. Click "Get Calendar"
4. The generated iCal file still includes events for practice sessions even though they were deselected

It appears that when either sprint race is selected, the practice session is included in the calendar, even when the practice is not selected. A feature race or qualifying only iCal does not have this issue.

**Comment by jmcgreevy42** [comment]
The underlying issue was the "p" key for practice was mating the letter p in "s**p**rint1" and "s**p**rint2", so it added practice sessions to the sprint calendars.

**Comment by ay8s** [comment]
Thanks @jmcgreevy42. Got this deploying now. 👏 

@all-contributors please add @jmcgreevy42 for bug.
