### ISSUE TITLE
Setup analytics conversions

### ISSUE THREAD

**Issue by si** [sportstimes/f1#60]
I want to understand what users are doing on the site as bounce rate seems high but I assume it’s due to it being an SPA so will look to setup one or more of the following metrics in GA

- [x] Add these race times > Download 
- [x] Pick sessions
- [x] Set a reminder + duration
- [x] Expand collapse races
- [x] Timezone change > drop down > apply
- [x] Translate options
- [x] Buy us a coffee
- [x] Vercel

**Comment by si** [comment]
I've setup the first goal to understand how it works with the Generate Calendar page

![Generate Calendar GA Goal](https://user-images.githubusercontent.com/18108/84503809-ca839a80-acb2-11ea-8b3c-bd60da67b756.png)

**Comment by ay8s** [comment]
Got these implemented in the multi-site setup in Plausible. 

Calendar generation is sent as one event with each option passed so we can see the most popular choices. Rather than for any change. 

Then another event for each download option.
