### ISSUE TITLE
Sprint qualifying is shown as "localization:schedule.sprintQualifying"

### ISSUE THREAD

**Issue by mzso** [sportstimes/f1#639]
Hi!

The site automatically chooses my language, but apparently this text is missing.

At the very least it should fall back to English, in my opinion.

By the way, it should be "Sprintkvalifikáció" in Hungarian.

**Comment by mzso** [comment]
PS:
I know it's "Időmérő" for Qualifying, but that only means "time measuring", which is not appropriate in this case.

PPS: Going by the above, it probably should be "Időmérő edzés" for qualifying since "edzés" means session in this case.
(Two separate words unlike for free practice)

**Comment by sarathcodes** [comment]
This is fixed via #710
