### ISSUE TITLE
Email digests

### ISSUE THREAD

**Issue by si** [sportstimes/f1#7]
I know it's not exactly cutting edge tech but I still think emails are one of the most engaging mediums with people.

Could we setup a newsletter to send weekly reminders of upcoming races, maybe even attach an ICS file or link to download so we can track engagement?

I've used Mailchimp in the past but open to suggestions.

**Comment by ay8s** [comment]
Started here https://github.com/sportstimes/f1/tree/feature/email-digests

**Comment by si** [comment]
Ooh, just seen the PR with this in. How are you planning to trigger/populate emails?

**Comment by ay8s** [comment]
@si Manual for now. More a heads up for the weekend with local track/utc times with a link to open the site for their timezone.

**Comment by ay8s** [comment]
Deployed 👍
