### ISSUE TITLE
Site leaks data to cache storage

### ISSUE THREAD

**Issue by FINDarkside** [sportstimes/f1#702]
Every time you load this page the service worker puts around 4-6MB of data to your cache storage without cleaning anything. I only noticed because this page was storing **3 GB** of data on my disk. Unregistered service worker, cleared cache storage and can still reproduce.

**Comment by ay8s** [comment]
Thanks for the issue @FINDarkside. We definitely had an issue a few months ago where the site was caching each of the Calendar files. This has been resolved, I'm not quite seeing the cache increase each visit like you describe. Would you be up for shooting over a quick screen recording or screenshot of 3-4 visits?

**Comment by FINDarkside** [comment]
My bad, cannot reproduce anymore. The old service worker probably didn't unregister until chrome restart or something even though I thought I made sure it had updated.
