### ISSUE TITLE
Incorrect dates for all F2 sessions in Saudi Arabia and Abu Dhabi

### ISSUE THREAD

**Issue by lerhond** [sportstimes/f1#713]
All dates for F2 in Saudi Arabia and Abu Dhabi are one day early - Thursday December 2 instead of Friday December 3, etc. Other than this one day difference, I think session times look correct.

**Comment by ay8s** [comment]
@lerhond Thanks for the heads up. Looks like the F2 site is completely wrong. Will correct this shortly based on the F1 Weekend Schedules.

**Comment by ay8s** [comment]
Should be fixed now. 👍
