### ISSUE TITLE
Broken link in footer

### ISSUE THREAD

**Issue by xta** [sportstimes/f1#720]
Nice work guys. Last race of the season is here.

In the footer, this link for Ant Williams is broken: http://abitgone.co.uk/

**Comment by si** [comment]
That's the end of that chapter. We'll mark this issue as Anthony William's legacy contributing to the project. 🪦

**Comment by ay8s** [comment]
@si I'm gonna update the readme so he's still mentioned 👍  😄

**Comment by xta** [comment]
Thanks all 👍 

I don't know Ant Williams. I was simply reporting a broken link.
