### ISSUE TITLE
API Error for year 2022 - Invalid SSL certificate

### ISSUE THREAD

**Issue by indigo-dev** [sportstimes/f1#759]
Is there any issue with your web-server's certificates? Fetching 2021 calendar works fine, but 2022 gives me some invalid SSL certificate error.
Happens when calling
https://f1calendar.com/api/year/2022

**Comment by ay8s** [comment]
@indigo-dev Not seeing any issues on our side in multiple browsers. Do you see it occurring elsewhere on the site at all?

**Comment by indigo-dev** [comment]
![image](https://user-images.githubusercontent.com/11189868/148601117-6ec192b5-2bd6-44f0-a1cf-c4203dcd8aca.jpeg)

This is what I get from all browsers and devices when calling API via https://f1calendar.com/api/year/2022

Maybe that's just the symptom of something different.
Aren't the 2022 dates but yet available via your API? I'm pretty sure my app already loaded it successfully the last weeks.
As mentioned 2021 works https://f1calendar.com/api/year/2021

**Comment by Mauricevb** [comment]
I see the same error when changing the language on the homepage.

**Comment by ay8s** [comment]
Thanks @Mauricevb @indigo-dev. Do you see the same now? 

Looks like some configuration changes between Cloudflare and Vercel which may have knocked things out.

**Comment by indigo-dev** [comment]
Many thanks, everything seems back in working mode
