### ISSUE TITLE
Add Romanian translation

### ISSUE THREAD

**Issue by a3drian** [sportstimes/f1#780]
Hi guys. Romanian translation is available in this archive: [ro.zip](https://github.com/sportstimes/f1/files/7949037/ro.zip).

Just extract the archive over the root folder, as I have already modified `i18n.json`.

**Comment by ay8s** [comment]
Thanks @a3drian 👍  

Will deploy to the site shortly.

**Comment by ay8s** [comment]
@all-contributors please add @a3drian for translations.

**Comment by ay8s** [comment]
This is merged 👍
