### ISSUE TITLE
Implement F1 Sprint Quali option for calendar

### ISSUE THREAD

**Issue by david235986** [sportstimes/f1#786]
Add an option for separate sprint qualifying sessions on https://f1calendar.com/generate

**Comment by ay8s** [comment]
Thanks @david235986. This is something we're still considering and planning for as it adds another level of complexity.

We need to find a solution that keeps existing subscribers with a working calendar, serving both traditional and sprint qualifying sessions along with a new setup for separate options. We also don't want to continue serving all of these versions indefinitely.

This is a little easier now as I've been separating the calendar file generation from the site itself to a separate workflow. So watch this space. 👍

**Comment by ay8s** [comment]
@david235986 This is now available 👍
