### ISSUE TITLE
Romanian translation issues

### ISSUE THREAD

**Issue by a3drian** [sportstimes/f1#805]
Hi guys. After you've added the translation I noticed some text strings were off so I corrected them - [ro - localization.zip](https://github.com/sportstimes/f1/files/8034408/localization.zip).

I have also noticed some issues with diacritics in the headers, see the underlined characters in this image:
![image](https://user-images.githubusercontent.com/38135936/153246393-fb4ad604-e46d-47eb-a886-efbdac5cace7.png)

It looks like it might only be affecting the headers or texts written in all caps, but I cannot say for sure.

**Comment by topscoder** [comment]
This is a font issue. Seems these characters are not available in this particular font (`Leaguespartan`). I see this (alternative?) League Spartan font supports Romanian language though: https://github.com/theleagueof/league-spartan
