### ISSUE TITLE
Can't find variable: ccalendarBaseURL

### ISSUE THREAD

**Issue by SkYNewZ** [sportstimes/f1#844]
Hello! To get ready for the upcoming season, I wanted to use this to have the events in my calendar.

However I got this error "Unhandled Promise Rejection: ReferenceError: Can't find variable: ccalendarBaseURL".
Tested on Firefox, Chromium and Safari.

In advance, thank you
And thank you for this very useful app.

**Comment by ay8s** [comment]
Thanks @SkYNewZ. Spotted the cause. Will have a fix for that deployed shortly.
