### ISSUE TITLE
country as a new key to db

### ISSUE THREAD

**Issue by Tsingis** [sportstimes/f1#865]
Would be nice addition even though the info can be enriched from name, location and/or coordinates.

**Comment by ay8s** [comment]
@Tsingis Is this so it can be used via the API? 👍

**Comment by Tsingis** [comment]
> @Tsingis Is this so it can be used via the API? 👍

I didn't really look deep into how the db files are used. At quick glance (by commit history and content) they 
seem to act as the source of truth and are maintained regularly. If addition does not benefit the project, my "request" is not that important.
