### ISSUE TITLE
Indycar Race 2 Incorrect Year (2023 vs 2022)

### ISSUE THREAD

**Issue by maxgubler** [sportstimes/f1#872]
https://github.com/sportstimes/f1/blob/372a409ccc5f09779cc28bf80cda917edb1174da/_db/indycar/2022.json#L29

Also, see this for race data:
https://indycar.roktcalendar.com/schedule
https://indycar.roktcalendar.com/api/calendarevents?calendarId=f3d5ebad-d272-e511-a14c-063521276427

**Comment by ay8s** [comment]
Thanks @maxgubler. Just deploying 👍
