### ISSUE TITLE
[Suggestion] Expand Current / "Next" Race by Default

### ISSUE THREAD

**Issue by Horridge** [sportstimes/f1#890]
I suspect the majority of visitors to https://f1calendar.com/ are interested only in seeing the times of the current, or "Next" race. Therefore I suggest that this race section be expanded by default.

1. Navigate to https://f1calendar.com/
2. Observe all accordian sections are collapsed (including the current / "Next" race)

![expandCurrentRace](https://user-images.githubusercontent.com/26923933/160235327-28f60709-4f01-4228-a512-18035764f981.png)

**Comment by ay8s** [comment]
Thanks for bringing this up. Got this ready to deploy 👍 
https://github.com/sportstimes/f1/pull/913

**Comment by Horridge** [comment]
Looks good, "Next' race is now expanded by default; tested on https://f1calendar.com/ 

Thanks
