### ISSUE TITLE
Localised timezones to include daylight saving adjustments

### ISSUE THREAD

**Issue by tomjnoble** [sportstimes/f1#906]
Would it be possible to add timezones for daylight savings? e.g Currently the UK is using BST yet the default time-zone for Europe/London is GMT +0.  (yes I know GMT+1 has the same effect, I'm just thinking of ease of use; not having to change the setting every visit).

**Comment by ay8s** [comment]
@tomjnoble I don't believe you need to change the setting each visit. I think its just a case that the label is incorrect. If you switch between London and Reykjavik for example the time adjusts as Reykjavik is GMT+0 while London is currently +1.

I'll see if there's a better way to generate those labels.
