### ISSUE TITLE
[Suggestion] Have an option to not add the UTC times in the e-mail body

### ISSUE THREAD

**Issue by fabioxgn** [sportstimes/f1#916]
I got confused by it multiple times because I forget that the times are UTC. For me, only receiving the notification with the dates and the button to check the local time would have the same function, the e-mail body could be something like this:

![image](https://user-images.githubusercontent.com/1084729/162434103-7e4e788a-a251-4600-a24a-e3058e5ad47e.png)

Would that be possible?

**Comment by ay8s** [comment]
We no longer include the times in the email and instead point directly to the site just to avoid confusion. 👍
