### ISSUE TITLE
Generate calendar link forgets language

### ISSUE THREAD

**Issue by si** [sportstimes/f1#97]
**Expected Behaviour**

Given I’ve chosen a different language
When I click the Generate Calendar link
Then I should see the page translated in the select language. 

**Actual Behaviour**

Given I’ve chosen a different language
When I click the Generate Calendar link
Then it falls back to EN default.

**Comment by ay8s** [comment]
@si When do you see it default back to EN? If I load up a different language and tap the Add to cal link it remains in the correct language for me.

**Comment by si** [comment]
Steps to reproduce:

1. Open Chrome/iOS 
2. Go to f1calendar.com
3. Open drop down for Langs
4. Select _FR_
5. Tap “_Ajouter ces dates et horaires de Grand Prix à votre calendrier_.” 
6. Loads f1calendar.com/generate

**Comment by si** [comment]
I’d love to try fix it myself but still need a developer laptop I can use (waiting for my birthday gift!) 🤓

**Comment by ay8s** [comment]
Aha, found it. Mobile specific issue, hence me being all "it works for me" :P 

Will fix shortly.

**Comment by si** [comment]
Cool! Strange how the behaviour is limited to mobile - is the trigger bound to a desktop only event?

**Comment by ay8s** [comment]
We show the link outside of the bar on mobile but we were missing the logic to correct the link with the additional locale. https://github.com/sportstimes/f1/pull/98/files
